services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: anchor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anchor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  anchor:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: anchor
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://anchor:password@postgres:5432/anchor
      - JWT_SECRET=supersecretkey

volumes:
  postgres_data:
